tox.ini 更新
### flake8 の E203 を検知対象外
black が `:` の前に半角スペースを設定するように修正しようとする為です。

black の修正の方が可視性が高いと判断しました。

### mypy で --ignore-missing-imports オプション追加

mypy によるチェックで以下エラーがインストールライブラリに対して出力されます。
これを回避すべく、 --ignore-missing-imports を設定します。

```
$ mypy .
talk/speech_recognizer.py:1: error: Cannot find implementation or library stub for module named "speech_recognit
ion"
```